"""Read/render/validate /etc/hosts — static name → address mappings.

Each data line is an IP address followed by one or more hostnames. Parsing,
validation and rendering are pure and CI-testable; the backend re-validates and
writes the whole file atomically. A bad /etc/hosts can break local name
resolution, so addresses must be real IPs and every name a valid hostname.
"""

from __future__ import annotations

import ipaddress
import re
from dataclasses import dataclass, field

HOSTS_PATH = "/etc/hosts"
HOSTS_HEADER = "# /etc/hosts: generated by GeST"

# One hostname label group (RFC 1123), optionally dotted.
_NAME_RE = re.compile(
    r"\A[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?"
    r"(\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*\Z"
)


@dataclass(slots=True)
class HostsEntry:
    address: str
    names: list[str] = field(default_factory=list)


def valid_host_address(address: str) -> bool:
    try:
        ipaddress.ip_address(address)
        return True
    except ValueError:
        return False


def valid_host_name(name: str) -> bool:
    return bool(_NAME_RE.match(name)) and len(name) <= 253


def valid_entry(entry: HostsEntry) -> bool:
    return (
        valid_host_address(entry.address)
        and bool(entry.names)
        and all(valid_host_name(n) for n in entry.names)
    )


def valid_hosts(entries: list[HostsEntry]) -> bool:
    return bool(entries) and all(valid_entry(e) for e in entries)


def parse_hosts(text: str) -> list[HostsEntry]:
    """Parse /etc/hosts text into entries (blank/comment lines skipped)."""
    entries: list[HostsEntry] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        parts = stripped.split()
        if len(parts) >= 2:
            entries.append(HostsEntry(parts[0], parts[1:]))
    return entries


def render_hosts(entries: list[HostsEntry]) -> str:
    """Render entries as a tab-separated /etc/hosts (with a header)."""
    lines = [HOSTS_HEADER]
    lines.extend(f"{e.address}\t{' '.join(e.names)}" for e in entries)
    return "\n".join(lines) + "\n"


def default_hosts(hostname: str = "") -> list[HostsEntry]:
    """The Handbook's baseline: loopback → ``localhost`` (v4 + v6), plus the host's
    own name on ``127.0.1.1`` (the Debian/systemd convention) when given, so the
    machine resolves its own name even before the network is up."""
    entries = [HostsEntry("127.0.0.1", ["localhost"]), HostsEntry("::1", ["localhost"])]
    if hostname and valid_host_name(hostname):
        entries.append(HostsEntry("127.0.1.1", [hostname]))
    return entries


def current_hosts(path: str = HOSTS_PATH) -> list[HostsEntry]:
    try:
        with open(path, encoding="utf-8") as fh:
            return parse_hosts(fh.read())
    except OSError:
        return []
