"""Read/render/validate /etc/resolv.conf — DNS nameservers + search domains.

The stub resolver's config: ``nameserver <ip>`` lines and an optional
``search <domain…>`` line. Parsing and validation are pure and CI-testable; the
backend does the privileged write. Note that on a system running a resolv.conf
manager (dhcpcd, NetworkManager, openresolv) a direct write may be overwritten —
which is exactly right for the install path, and the UI says so on a live system.
"""

from __future__ import annotations

import ipaddress
import re

RESOLV_PATH = "/etc/resolv.conf"
RESOLV_HEADER = "# /etc/resolv.conf: generated by GeST"

# A DNS domain: dot-separated labels (RFC 1123).
_DOMAIN_RE = re.compile(
    r"\A[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?"
    r"(\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*\Z"
)


def valid_nameserver(ip: str) -> bool:
    """True for a valid IPv4 or IPv6 nameserver address."""
    try:
        ipaddress.ip_address(ip)
        return True
    except ValueError:
        return False


def valid_search_domain(domain: str) -> bool:
    return bool(_DOMAIN_RE.match(domain)) and len(domain) <= 253


def valid_resolv(nameservers: list[str], search: list[str]) -> bool:
    """A resolv.conf must have at least one valid nameserver; domains optional."""
    return (
        bool(nameservers)
        and all(valid_nameserver(ns) for ns in nameservers)
        and all(valid_search_domain(d) for d in search)
    )


def parse_resolv(text: str) -> tuple[list[str], list[str]]:
    """Parse resolv.conf into ``(nameservers, search_domains)``."""
    nameservers: list[str] = []
    search: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        parts = stripped.split()
        if len(parts) < 2:
            continue
        if parts[0] == "nameserver":
            nameservers.append(parts[1])
        elif parts[0] in ("search", "domain"):
            search.extend(parts[1:])
    return nameservers, search


def render_resolv(nameservers: list[str], search: list[str]) -> str:
    """Render a resolv.conf (header, optional search line, nameserver lines)."""
    lines = [RESOLV_HEADER]
    if search:
        lines.append("search " + " ".join(search))
    lines.extend(f"nameserver {ns}" for ns in nameservers)
    return "\n".join(lines) + "\n"


def current_resolvers(path: str = RESOLV_PATH) -> tuple[list[str], list[str]]:
    try:
        with open(path, encoding="utf-8") as fh:
            return parse_resolv(fh.read())
    except OSError:
        return [], []
