"""CI-safe tests for the DNS/hosts core: resolv.conf and /etc/hosts parsing,
validation (IPv4/IPv6 + hostnames), and rendering round-trips."""

from gest.core.network import hosts, resolv

# --- resolv.conf ------------------------------------------------------------

def test_resolv_parse_nameservers_and_search():
    text = ("# comment\n"
            "nameserver 1.1.1.1\n"
            "nameserver 2606:4700:4700::1111\n"
            "search lan example.com\n"
            "domain corp.internal\n")
    nameservers, search = resolv.parse_resolv(text)
    assert nameservers == ["1.1.1.1", "2606:4700:4700::1111"]
    assert search == ["lan", "example.com", "corp.internal"]


def test_valid_nameserver_v4_v6_and_reject():
    assert resolv.valid_nameserver("8.8.8.8")
    assert resolv.valid_nameserver("2001:4860:4860::8888")
    for bad in ("", "8.8.8", "999.1.1.1", "not-an-ip", "1.1.1.1/24"):
        assert not resolv.valid_nameserver(bad)


def test_valid_resolv_requires_a_nameserver_and_good_domains():
    assert resolv.valid_resolv(["1.1.1.1"], [])
    assert resolv.valid_resolv(["1.1.1.1"], ["lan", "a.b.c"])
    assert not resolv.valid_resolv([], [])                     # no nameserver
    assert not resolv.valid_resolv(["bad"], [])                # bad ip
    assert not resolv.valid_resolv(["1.1.1.1"], ["bad_domain!"])  # bad domain


def test_render_resolv_round_trips():
    text = resolv.render_resolv(["1.1.1.1", "9.9.9.9"], ["lan"])
    assert text.startswith("# /etc/resolv.conf: generated by GeST\n")
    assert "search lan\n" in text
    assert "nameserver 1.1.1.1\nnameserver 9.9.9.9\n" in text
    ns, se = resolv.parse_resolv(text)
    assert (ns, se) == (["1.1.1.1", "9.9.9.9"], ["lan"])


def test_current_resolvers_reads_file(tmp_path):
    p = tmp_path / "resolv.conf"
    p.write_text("nameserver 1.0.0.1\n")
    assert resolv.current_resolvers(str(p)) == (["1.0.0.1"], [])
    assert resolv.current_resolvers(str(tmp_path / "missing")) == ([], [])


# --- /etc/hosts -------------------------------------------------------------

def test_hosts_parse_skips_comments_and_blanks():
    text = "127.0.0.1 localhost host1\n\n# a comment\n::1  localhost\n"
    entries = hosts.parse_hosts(text)
    assert [(e.address, e.names) for e in entries] == [
        ("127.0.0.1", ["localhost", "host1"]),
        ("::1", ["localhost"]),
    ]


def test_host_address_and_name_validation():
    assert hosts.valid_host_address("192.168.0.1")
    assert hosts.valid_host_address("fe80::1")
    assert not hosts.valid_host_address("192.168.0.256")
    assert hosts.valid_host_name("host1")
    assert hosts.valid_host_name("db.internal.example")
    for bad in ("", "bad_name", "-x", "a b"):
        assert not hosts.valid_host_name(bad)


def test_valid_entry_and_hosts():
    good = hosts.HostsEntry("10.0.0.1", ["gw", "gateway.lan"])
    assert hosts.valid_entry(good)
    assert not hosts.valid_entry(hosts.HostsEntry("10.0.0.1", []))       # no names
    assert not hosts.valid_entry(hosts.HostsEntry("nope", ["x"]))        # bad ip
    assert hosts.valid_hosts([good])
    assert not hosts.valid_hosts([])                                     # empty
    assert not hosts.valid_hosts([good, hosts.HostsEntry("bad", ["x"])])


def test_render_hosts_round_trips():
    entries = [hosts.HostsEntry("127.0.0.1", ["localhost"]),
               hosts.HostsEntry("::1", ["localhost", "ip6-localhost"])]
    text = hosts.render_hosts(entries)
    assert text.startswith("# /etc/hosts: generated by GeST\n")
    assert "127.0.0.1\tlocalhost\n" in text
    assert "::1\tlocalhost ip6-localhost\n" in text
    reparsed = hosts.parse_hosts(text)
    assert [(e.address, e.names) for e in reparsed] == \
        [(e.address, e.names) for e in entries]


def test_default_hosts_is_loopback():
    assert [(e.address, e.names) for e in hosts.default_hosts()] == [
        ("127.0.0.1", ["localhost"]),
        ("::1", ["localhost"]),
    ]
    assert hosts.valid_hosts(hosts.default_hosts())


def test_default_hosts_adds_the_hostname():
    entries = {e.address: e.names for e in hosts.default_hosts("workshop")}
    assert entries["127.0.0.1"] == ["localhost"]
    assert entries["127.0.1.1"] == ["workshop"]              # self-resolution
    # no 127.0.1.1 row without a name, and an invalid name is ignored
    assert all(e.address != "127.0.1.1" for e in hosts.default_hosts())
    assert all(e.address != "127.0.1.1" for e in hosts.default_hosts("bad host!"))


def test_current_hosts_reads_file(tmp_path):
    p = tmp_path / "hosts"
    p.write_text("127.0.0.1 localhost\n")
    assert [(e.address, e.names) for e in hosts.current_hosts(str(p))] == \
        [("127.0.0.1", ["localhost"])]
    assert hosts.current_hosts(str(tmp_path / "missing")) == []
